from multiviewcollection import IMultiviewCollectionPortlet
from multiviewcollection import Assignment
from multiviewcollection import Renderer
from multiviewcollection import AddForm
from multiviewcollection import EditForm